### ISSUE TITLE
Windows, local history copies are created, but cannot be found and displayed in the list

### ISSUE THREAD

**Issue by xorcus** [Nicolab/atom-local-history#10]
Directory opened in Atom is `C:\Projects\my-project`. The history is being created in `%USERPROFILE%\.atom\local-history\c\Projects\my-project\<timestamp>_myfile.txt`, but when I toggle `Local History: Current File` in the Command palette (`Ctrl+Shift+P`), it says `No matches found` and below that the full (correct) path to `%USERPROFILE%\.atom\local-history`

One example of a local history file: `2015-1-27_1-49-13 PM_myfile.txt`
Maybe it's caused by a mismatch in timestamp formatting (e.g. by the space preceding PM)?

**Comment by Nicolab** [comment]
Hello,

it's related to #9 I'll do it as soon as possible

**Comment by xorcus** [comment]
thx! closing the issue
