### ISSUE TITLE
Problem running difftool

### ISSUE THREAD

**Issue by niallobrien** [Nicolab/atom-local-history#14]
I get this error:
Command error: ksdiff "/Users/niall/test" "/Users/niall/.atom/local-history/Users/niall/Documents/2015-02-26_10-38-38 PM_test"

Error details: Error: Command failed: /bin/sh -c cd /Users/niall && ksdiff "/Users/niall/test" "/Users/niall/.atom/local-history/Users/niall/Documents/2015-02-26_10-38-38 PM_test" /bin/sh: ksdiff: command not found

However, if I run /bin/sh -c cd /Users/niall && ksdiff "/Users/niall/test" "/Users/niall/.atom/local-history/Users/niall/Documents/2015-02-26_10-38-38 PM_test" from the command line, it works fine.

**Comment by Nicolab** [comment]
This may be related to the configuration of your environment (process env path).
Try with the absolute path of the command `ksdiff` (example: `/usr /local/bin/ksdiff`)

It seems that others have encountered a similar error with Atom:
https://discuss.atom.io/t/how-to-execute-node-js-child-process-from-package/4880/8

For info, the command is executed with `require("child_process").exec`

**Comment by niallobrien** [comment]
@Nicolab Awesome, thanks for that.
`which ksdiff` revealed my path and I followed your advice - works perfectly. :)

I still miss the local history view from Webstorm though.

**Comment by Nicolab** [comment]
:smiley:
