### ISSUE TITLE
Purge confirmation

### ISSUE THREAD

**Issue by Trudko** [Nicolab/atom-local-history#15]
Hi :). how about adding confirming dialog for purge command? Maybe is just me, but I've accidentally purge current file.(Purge command comes at top of the list)

**Comment by Nicolab** [comment]
Hello,

it does not matter, purging keeps 30 days of revisions (configurable). Only the old revisions are purged.

The goal is to purge occasionally to avoid too much revisions. The best would be [automate this command](https://github.com/Nicolab/atom-local-history#todo).

**Comment by Trudko** [comment]
Well setting high number of days might work but what if you return to file you didn't touch for long time? You run into risk there. I think number of revision would be help full there. 

How do you think the automate purging would work? Can we use serialization to store last time history was purged maybe?

**Comment by Nicolab** [comment]
It's not 30 calendar days but 30 days of revision (accumulated).
Sorry for my bad english ;)

Example:

 * 2015-01-01_11-00-00_notes.md
 * 2015-01-01_12-00-00_notes.md
 * 2015-02-10_11-00-00_notes.md
 * 2015-03-12_09-00-00_notes.md

Only 3 days of revision (2015-01-01, 2015-02-10, 2015-03-12).
You can purge several years later, it will always keep at least 30 days of backup. In the example above 3 days are kept (4 files).

May be, the ideal would be also to limit the number of files per day.
