### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by HolyHaddock** [Nicolab/atom-local-history#18]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
LocalHistoryView.findLocalHistory (/Users/ham/.atom/packages/local-history/lib/local-history-view.js:127:7)
```

**Comment by Nicolab** [comment]
Please, upgrade to the last version of local-history.
