### ISSUE TITLE
Problem with filenames including underscore in name

### ISSUE THREAD

**Issue by nmarcal** [Nicolab/atom-local-history#20]
Some context first, i'm using Rails, and most of the files use underscore in name (e.g. application_helper.rb), so they aren't being listed in history, i had a look in your code and the problem seems to in getOriginBaseName ... the filename is being get by the last index of underscore ... so in my example ... it only gets **helper.rb** instead of **application_helper.rb** ... i was trying some things and i think that one solution could be using an regular expression to remove the date from the filename something like: basePath.replace(/([0-9]{4}-[0-9]{2}-[0-9]{2})_([0-9]{2}-[0-9]{2}-[0-9]{2})_/g, '') ... i'm not expert in regex so ... maybe could exist a better approach

**Comment by JohnMurga** [comment]
Fixed by the following :+1: https://github.com/JohnMurga/atom-local-history/commit/63aff3bd0d593e50228d1a9fdcc26c497205cf1e

**Comment by Nicolab** [comment]
Fixed by #31 and released to v3.2.3, thanks @JohnMurga :wink:
