### ISSUE TITLE
Save history also for unsaved files

### ISSUE THREAD

**Issue by davisein** [Nicolab/atom-local-history#37]
For unsaved files it would be useful to also save the history.

We cannot use the fullpath. So putting some random number as path in the right project would do the trick.

For me, it would be an awesome feature to have some track of older unsaved tabs.

**Comment by Nicolab** [comment]
Hello,

thanks for your suggestion but this feature would reduce the performance (I/O disk is slow) and significantly increase the number of stored files (and the global history size).

The [goal](https://github.com/Nicolab/atom-local-history#why) is only to save the file revision, not the buffer revision (Atom has already a text buffer history).

This will be another package for another goal.

**Comment by davisein** [comment]
Ok, thanks for the fast answer and congratualtions for the package!

**Comment by Nicolab** [comment]
Thanks :wink:
