### ISSUE TITLE
Add optional feature to save history of a file without saving it

### ISSUE THREAD

**Issue by wdanilo** [Nicolab/atom-local-history#40]
Hello!
It would be really great to add feature to save history of a file based on time period. Sometimes Atom crashes and it would be so useful if this plugin will save a file every edit / couple of seconds and keep history for some given time diff, like every minute or so.

**Comment by Nicolab** [comment]
Hello,

thanks for your suggestion but this feature would reduce the performance (I/O disk is slow) and significantly increase the number of stored files (and the global history size).

For now I have never encountered this problem, I save (ctrl-s) very often (by reflex) and my Atom crash very rarely, may be another package based on tempory file would be more appropriate:
 * https://atom.io/packages/autosave
 * or https://atom.io/packages/autosave-plus

**Comment by wdanilo** [comment]
Atom not always provides the unsaved buffer - I encounter very often a situation when after crash every tab is closed without things being saved. I agree that hitting often `ctrl+s` is good, but even loosing 10 minutes of work, when you are designing some datatypes and thinking about it is a bad thing. Normally I hit `ctrl + s` very often, but sometimes you just dont want to do it.

I completely understand your worries about I/O performance and the history size, but as I've written before, there are simple solutions to it, namely:

1. make it optional
2. allow users set the time interval when each file should be saved (on modern SSD's saving a text file costs almost nothing)
3. allow users to set the interval between history revisions (so even if the file is saved each 10 seconds, the history would delete all versions but in the time interval of for example 5 minutes).

On the other hand, using some `auto-save` creates unnecessary re-compilation of everything and mess with errors window output. This is one of the reasons I prefer sometimes not to save the files so often - If I see that some errors occurred I prefer to fix the errors before invoking recompilation and loosing the information from the screen.

**Comment by Nicolab** [comment]
I understand, thank you for your feedback. Unfortunately, at this time, this is not an intended feature.
