### ISSUE TITLE
On Windows with ByeondCompare - after succesful compare its throwing error

### ISSUE THREAD

**Issue by Noitidart** [Nicolab/atom-local-history#42]
I'm getting some weird behavior here.

This is my setting for diff:

    "C:\Users\Mercurius\Desktop\Beyond Compare 4\BCompare.exe" "{revision-file}" "{current-file}"

When I do a diff it succesfully opens it.

But after I close the diff tool this error shows in atom:

```

Local history: difftool Command
Check the field value of difftool Command in your settings (local-history package).
Command error: "C:\Users\Mercurius\Desktop\Beyond Compare 4\BCompare.exe" "C:\Users\Mercurius\.atom\local-history\C\Users\Mercurius\Documents\GitHub\react-grid-layout\2016-05-21_3-19-40 PM_index.js" "C:\Users\Mercurius\Documents\GitHub\react-grid-layout\index.js"

Error details: Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "cd C:\Users\Mercurius\Documents\GitHub\react-grid-layout && "C:\Users\Mercurius\Desktop\Beyond Compare 4\BCompare.exe" "C:\Users\Mercurius\.atom\local-history\C\Users\Mercurius\Documents\GitHub\react-grid-layout\2016-05-21_3-19-40 PM_index.js" "C:\Users\Mercurius\Documents\GitHub\react-grid-layout\index.js""
index.js26:19
CRLFUTF-8JavaScriptmaster+65, -5
```

![](http://i.imgur.com/1hKZLCB.png)

Any idea why please?

**Comment by Nicolab** [comment]
Hello,

you can upgrade _local-history_ with the last version (v3.3.0) published to day.

Tell me if it's ok?

**Comment by Noitidart** [comment]
Thank you very much for the fast reply! (also for being so cool about those 3 bogus issues I made here haha)

I updated, then restarted atom but it gave me same error :(

![](http://i.imgur.com/wIHCoAX.png)

**Comment by Nicolab** [comment]
I think it comes from the command. Please, try directly the command in the Windows terminal.
When the command is ok in the terminal, copy the command in the _local-history_ setting by replacing the paths with `"{current-file}"` and `"{revision-file}"`.

Sorry, I do not have Windows to test.

**Comment by Noitidart** [comment]
It's real interesting, it's not giving me errors in the cmd.exe please see screencast - https://www.youtube.com/watch?v=ylSbTnDhUlU

I did notice something funny though. I don't know if related, but it seems to cd into a folder for no reason:

![](http://i.imgur.com/SjoAYey.png)

**Comment by Nicolab** [comment]
The `cd` is for working in the current directory (simpler in the case of saving new files).
I watched your screencast but I do not see why the command crashes at the end, sorry :(

May be the quotes suite `"cd "....""`

**Comment by Noitidart** [comment]
Thanks @Nicolab  very much for trying to help. I'll update you if I get it fixed :) The quotes didn't cause problem in the cmd.exe though, I am baffled haha but I'll keep you updated. :)

**Comment by Nicolab** [comment]
Ok thanks!
Good luck ;)
