### ISSUE TITLE
"& Close" label finnicky

### ISSUE THREAD

**Issue by Noitidart** [Nicolab/atom-local-history#43]
Affects v1.8

Make sure the "& Close" label shows on startup of the canvas editor. It's a bit finnicky right now.

Also the "& Close" is missing from the "Search" button.

**Comment by Noitidart** [comment]
Ohhh shoot I thought I was posting these issues in my repository! Whoops! Excuse that please is there a way to delete these?

**Comment by Nicolab** [comment]
Hello,

lol :smile: 
Github has no option to delete an issue.
