### ISSUE TITLE
Clicking "Change" crashes or doesnt work

### ISSUE THREAD

**Issue by Noitidart** [Nicolab/atom-local-history#44]
Clicking "Change" on the options for "Quick save dir" doesn't work - sometimes causes crash of firefox.

**Comment by Noitidart** [comment]
Ohhh shoot I thought I was posting these issues in my repository! Whoops! Excuse that please is there a way to delete these?

**Comment by Nicolab** [comment]
Hello,

lol :smile: 
Github has no option to delete an issue.
