### ISSUE TITLE
Right click/hotkey for bring element forward/backward

### ISSUE THREAD

**Issue by Noitidart** [Nicolab/atom-local-history#45]
Forgot to add this crucial feature in v1.8 - right click/hotkey for bring element forward/backward/backmost/frontmost

**Comment by Noitidart** [comment]
Ohhh shoot I thought I was posting these issues in my repository! Whoops! Excuse that please is there a way to delete these?

**Comment by Nicolab** [comment]
Hello,

lol :smile: 
Github has no option to delete an issue.
