### ISSUE TITLE
Automatic Purge

### ISSUE THREAD

**Issue by marco-roy** [Nicolab/atom-local-history#49]
Hey Nicolas,

Thanks for this package! I missed the feature from Eclipse.

Instead of implementing an automatic purge, there's a simple workaround that you could add to the documentation. Simply add this line to your `init.coffee` (_Edit > Init Script..._):

`atom.commands.dispatch(atom.views.getView(atom.workspace), 'local-history:purge');`

This way, the purge command will be called automatically every time atom starts.

**Comment by Nicolab** [comment]
Hello Marco,

Good idea :+1: 
I will add this as soon of possible.

Thanks!

**Comment by Nicolab** [comment]
Released in v4.2.0 :tropical_drink:
