### ISSUE TITLE
Error when using Araxis Merge as difftool

### ISSUE THREAD

**Issue by zeronil** [Nicolab/atom-local-history#51]
I use Araxis Merge and I set the Difftool Command to:

`compare "{current-file}" "{revision-file}"`

When the diff is performed, Araxis Merge opens with the files but in Atom there are two errors displayed that say "Command failed". 

If I copy the command generated by atom-local-history from the error message and paste it into a terminal window, there is no error in the terminal (just in Atom). 

`cd "/Users/paul/project" && compare "/Users/paul/project/file1.xml" "/Users/paul/.atom/local-history/Users/paul/project/2017-05-16_12-39-18_file1.xml"`

Not sure why an error is shown in Atom and not when copying the generated command into the terminal since in both cases Araxis Merge loads and displays the diff properly.

**Comment by Nicolab** [comment]
Thanks for your report.

The messages only indicate  "Command failed"? Nothing else?

**Comment by zeronil** [comment]
The only other message is "Check the field value of difftool Command in your settings (local-history package)." I have it set to:

`compare "{current-file}" "{revision-file}"`

Araxis Merge does open with this command and displays the current and selected file, it's just that 2 or 3 error messages pop up in Atom whenever I do a compare (and I have to manually close each). It doesn't say what the specific error is, but could it be due to something that the Araxis Merge "compare" command returns? Also, it appears that the Araxis Merge Compare command line uses AppleScript for automation, so I don't know it that could be related.

Here's a link to the documentation for the Compare command line utility:

[Araxis Merge Command Line Utility Documentation](https://www.araxis.com/merge/documentation-os-x/command-line.en )

There's a 30 day free trial if you want to try it ....

**Comment by Nicolab** [comment]
It seems that the Araxis Merge command returns an error when is not executed in a terminal. If it works in your terminal, Perhaps there are a dependency of an environment variable or other.

I will not debug Araxis Merge, I'm on Linux and busy. I just added an option to disable the errors in the message panel. Also, I added a little error report in the devTool. 

You can update the `local-history` package to v.4.3.0, then uncheck this option in the settings of `local-history` :wink:

**Comment by zeronil** [comment]
The new option to suppress diff tool errors works great! I sent a small donation to thank you for your work :-)

**Comment by Nicolab** [comment]
Oh lovely! 

Thanks :+1:
