### ISSUE TITLE
didn't show history

### ISSUE THREAD

**Issue by yesilhuseyin** [Nicolab/atom-local-history#52]
file history didn't show from the last update.

**Comment by Nicolab** [comment]
* What is your Atom version and OS?
 * Do you have any error message or logs in the devtools?

**Comment by yesilhuseyin** [comment]
Windows 10 + Atom 1.17.2
No error or alert.

stay like this

http://imgur.com/7TAtMxd

thnx for help.

**Comment by Nicolab** [comment]
Any logs in the devtool?

**Comment by Trudko** [comment]
@Nicolab Not sure if same problem, but the list doesn't show properly for Material UI theme. The files are loaded they just seems to be hidden.

**Comment by Nicolab** [comment]
local-history use the default style of Atom, I did not notice any display problems when I change the theme.
Please, can you test with another theme?

Windows also?

**Comment by Trudko** [comment]
@Nicolab I've tested this on two different Atom installation under Windows where I've installed material UI syntax and UI theme, installed local history. Both had same problem. This works with other UI themes like Apex, One dark,  Atom dark.

**Comment by Nicolab** [comment]
OK thanks.
I have tested and I have the same issue only with the Material UI theme.
Same issue https://github.com/atom-material/atom-material-ui/issues/414 with another package in the Material UI theme.

If someone has a tips with this theme, feel free to add.

**Comment by yesilhuseyin** [comment]
@Nicolab yes, I used Atom Material design. Default theme doesn't do it.

**Comment by Nicolab** [comment]
Ok, thanks for your confirmation.

**Comment by yesilhuseyin** [comment]
Hİ again, I removed "overlay" class from list, fixed.

<div class="select-list local-history" is="space-pen-div">

thnx for help :)

**Comment by Nicolab** [comment]
Great!
Thanks for your feedback :+1: 

ping @Trudko

**Comment by dbethel** [comment]
I found another solution that got me up and running. I added the following to the atom stylesheet.

`.overlay, atom-panel.modal {
  overflow: inherit;
}`

https://github.com/h3imdall/ftp-remote-edit/issues/79#issuecomment-321914585
