### ISSUE TITLE
What is diff tool for and how to use?

### ISSUE THREAD

**Issue by DaSniper12** [Nicolab/atom-local-history#54]
Hello Nicolab or anyone,

I use your local history package and I am wondering what is the diff tool for and how to use it, windows.

Regards,
Aditya A

**Comment by Nicolab** [comment]
Hello,

Any diff tool which can be started with a command. See the [doc](https://github.com/Nicolab/atom-local-history#difftoolcommand).

I use [Meld](http://meldmerge.org/) (it's the value by default of local-history), it works on Windows and Linux.

**Comment by DaSniper12** [comment]
Hello,

Okay, I see meld, but I think I need to rephrase my question, What is a diff tool?

Regards

**Comment by Nicolab** [comment]
In this case, when you have two or more versions of a file. It help for comparing and merging a content.

For more details:
 * http://meldmerge.org
 * http://winmerge.org
 * https://www.google.com/search?q=diff+tool
 * https://en.wikipedia.org/wiki/Diff_utility
