### ISSUE TITLE
"meld" command missing

### ISSUE THREAD

**Issue by iGadget73** [Nicolab/atom-local-history#58]
Since the update of atom to 1.40.0 accessing an old version of a file doesn't work anymore. The error message says:

> Check the field value of difftool Command in your settings (local-history package).
Command error: meld "/…/_panels.scss" "/Users/…/.atom/local-history/Users/…2019-08-13_12-41-32__panels.scss"
> Error details: Error: Command failed: cd "/Users/…/roof" && meld "/Users/…/_panels.scss" "/Users/…/2019-08-13_12-41-32__panels.scss" /bin/sh: meld: command not found

(replaced parts of the paths with ellipsis to make anonymous)

So either the terminal command is wrong here (my research brought up, that its a windows command rather than a general terminal command) or I'm missing an installation of something I'm not aware of....
Any suggestions?

**Comment by Nicolab** [comment]
Hello,

It's not a Windows command (I'm on Linux), it's a default command to open Meld as a diff tool. You can add the command of your favorite diff tool.

**Comment by iGadget73** [comment]
Doesn't exist in my system anymore, seems to be fixed. Thx

**Comment by Nicolab** [comment]
Normal, it's just a default command. You can install `meld` or add you favorite diff tool. https://github.com/Nicolab/atom-local-history#difftoolcommand
