### ISSUE TITLE
[Feature Request] Save a backup On Changes of the file

### ISSUE THREAD

**Issue by Tahx** [Nicolab/atom-local-history#59]
Looks like this Github isn't maintained but I'll still post it, who knows.

You've been working on a file for days but you haven't saved it yet.
Of course you wouldn't do that, but in reality, you're so focused in your work, you simply forgot.

Would be great to also be able to decide whether you want your saved or unsaved file to be consistently backed up On Changes.

So for example, you type something, 2 seconds after you finishing typing it'll automatically save a backup.

**Comment by Nicolab** [comment]
Hello,

Thanks for your suggestion, it's already discussed here #37 

This feature would reduce the performance (I/O disk is slow) and significantly increase the number of stored files (and the global history size).

The [goal](https://github.com/Nicolab/atom-local-history#why) is only to save the file revision, not the buffer revision.

May be another package based on tempory file would be more appropriate:

https://atom.io/packages/autosave
or https://atom.io/packages/autosave-plus
