### ISSUE TITLE
local-history:difftool "{revision-file}" "{current-file}" opens blank file

### ISSUE THREAD

**Issue by manosnoam** [Nicolab/atom-local-history#61]
I've set in local-history settings to use my default diff tool (split-diff), as follow:
`local-history:difftool "{revision-file}" "{current-file}"`

But when trying  to compare, it opens a blank file.

Any workaround ?

**Comment by Nicolab** [comment]
In your example, the command is: `local-history:difftool`. The command should be a command system. https://github.com/Nicolab/atom-local-history#difftoolcommand

To execute an internal Atom command, I don't know, but if you find it, don't hesitate to show us

**Comment by manosnoam** [comment]
I tried meld plugin (which suppose to support calling it outside Atom), but "meld" has comparability issues on recent Atom 1.43. 
split-diff is working well, but it has no option to be called from shell command.

**Comment by Nicolab** [comment]
`meld` is a program, not an Atom plugin: https://meldmerge.org
It takes 2 files as argument, no matter where the command was executed and the diff tool you use:

```sh
meld "{revision-file}" "{current-file}"
```

local-history replaces `"{revision-file}" "{current-file}"` by the file paths.
