### ISSUE TITLE
original file is never saved in history

### ISSUE THREAD

**Issue by ballerburg9005** [Nicolab/atom-local-history#62]
It appears that this plugin only saves history files, for file saves that were done directly with Atom.

If the file was created elsewhere, or it was changed it in the meantime (e.g. via git pull), then this is not included in the history.

The plugin should not only put new saves into the history, but also the file it overwrote, if that file differs from the last history saved.

Otherwise it is a total nightmare: a history full of holes where no one knows what is missing.

**Comment by Nicolab** [comment]
This plugin does not replace GIT. It is a local-history plugin like other on other editors. It saves only a copy when a file is created or updated **via Atom**. This avoid an accident when saving a file, with a mistake and a commit too far for example.
It should be seen as a security while coding with Atom, between 2 commits.
Original file should be committed with a version control (like Git).

**Comment by ballerburg9005** [comment]
I think you misunderstood what I said, and maybe it is just a bug.

If I open a file and it does not save the original file in history, this is by no means a security feature. Since I cannot revert to the original file. You *always* want to save the file that you overwrite to history. You *never* really want to save the file that you have overwritten with to history. I mean you could, but what is the point?

What happens currently for me is the equivalent of this:

```
cp new_content old_content
cp new_content ~/.backup/old_content-`date +%s`
```

This is plain stupid. First it overwrites the content, then it saves the overwritten content in a backup history.

What should really happen is this:

```
cp old_content ~/.backup/old_content-`date +%s`
cp new_content old_content
```

I hope you understand now.
