### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by serkon** [Nicolab/atom-local-history#9]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\Serkan\AppData\Local\atom\app-0.175.0\resources\app\src\atom.js:55:11)
Object.activate (c:\Users\Serkan\.atom\packages\local-history\lib\local-history.js:43:9)
```

**Comment by Nicolab** [comment]
Ok thank you, I look at this weekend
